language: node_js
os:
  - osx
  - linux
node_js: 8

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - |
    echo ">>> Compile clojureVSCode"
    npm install
    npm run vscode:prepublish
    echo ">>> Run clojureVSCode unit tests"
    npm run test --silent
cache: npm
